#!/usr/bin/env ruby
require File.expand_path File.join( File.dirname(__FILE__), "../lib/wonkavision-sample")
require "wonkavision-sample/runner"

runner = Wonkavision::Sample::Runner.new(ARGV)
runner.run